global:
  pattern: multicloud-gitops
  secretLoader:
    disabled: false
  options:
    installPlanApproval: Automatic
    syncPolicy: Automatic
    useCSV: false
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
