clusterGroup:
  name: hub
  namespaces:
    - multicloud-gitops
    - vault
    - external-secrets-operator:
        operatorGroup: true
        targetNamespaces: []
    - external-secrets
  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
  applications:
    config-demo:
      name: config-demo
      namespace: multicloud-gitops
      path: charts/all/config-demo
    hello-world:
      name: hello-world
      namespace: multicloud-gitops
      path: charts/all/hello-world
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
