---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
    multiSourceRepoUrl: https://github.com/dminnear-rh/clustergroup-chart
    multiSourceTargetRevision: dont-create-subscriptions-without-names
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/dminnear-rh/clustergroup-chart
    clusterGroupChartGitRevision: dont-create-subscriptions-without-names
